### ISSUE TITLE
too many zp's are direct children of HP:0000118

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#777]
if you look at the most recent build of monarch with the latest zp.owl:
http://duckworth.crbs.ucsd.edu:9000/scigraph/graph/neighbors.json?id=HP:0000118&depth=1&blankNodes=false&direction=INCOMING&relationshipType=subClassOf

there are tons of ZP children of 'abnormal phenotype' (HP:0000118).  not sure what pipeline these relationships are coming from, but hope that @drseb or @cmungall can fix.

**Comment by cmungall** [comment]
Should be fixed by SciGraph/SciGraph#130

**Comment by ccondit** [comment]
Implemented in SciGraph but the ZP children are still present. Please assign back to me is this is an issue with SciGraph.

**Comment by cmungall** [comment]
The behavior is as expected, this is the logical structure of the ontology. Most of these ZPs have dual classification, under
1. An _abnormality-neutral_ grouping class, e.g.'mitotic G1 phase phenotype'
2. 'Abnormal phenotype'

Note that 1 and 2 do not stand mutually in a subsumption relationship; 1 is abnormality-neutral so cannot be placed under an 'abnormal phenotype'

We could either make the grouping classes explicitly abnormal, or make triads of neutral/abn/normal. Depends on our strategy for normals

**Comment by jmcmurry** [comment]
@cmungall please advise what needs to be done to close this ticket; thanks

**Comment by cmungall** [comment]
My general strategy is to open the ontology in Protege and investigate 
from there; if there are links that look incorrect I get an explanation 
from the reasoner.

**Comment by iamkoehler** [comment]
@cmungall could you clarify which ontology you mean by _the ontology_? Where can I find it?

**Comment by cmungall** [comment]
https://github.com/monarch-initiative/monarch-ontology/

However, you can start from deeper within the import hierarchy. Here http://purl.obolibrary.org/obo/upheno/vertebrate.owl would work

**Comment by iamkoehler** [comment]
thanks @cmungall 

The first thing I see are unsatisfiable statements in _monarch.owl_. See this screenshot:
![screen shot 2015-11-25 at 09 55 10](https://cloud.githubusercontent.com/assets/5172897/11392523/a4d6169e-935a-11e5-9f89-0879b7aaf0c8.png)

Is it correct that **part of** is a subproperty of **happens during**?

Another thing that I see in _vertebrate.owl_, is that the imports are not working correctly, such that the axioms required for inferences are not present. (Missing subclass axioms). For example for _abnormal(ly) decreased length enteric neuron_ the class _ZFA_0005775_ does not have any axiom annotations:

![screen shot 2015-11-25 at 10 02 09](https://cloud.githubusercontent.com/assets/5172897/11392711/bc00ec9e-935b-11e5-9ed4-d316f5117e18.png)
